export const songData = [
  {
    id: "1",
    no: "01",
    songName: "Popular",
    songImage: "coverarts/popular.jpeg",
    artist: "The Weeknd",
    imgtxt: "popular",
    month: "January",
  },
  {
    id: "2",
    no: "02",
    songName: "Agora Hills",
    songImage: "coverarts/agorahills.png",
    artist: "Doja Cat",
    imgtxt: "agorahills",
    month: "January",
  },
  {
    id: "3",
    no: "03",
    songName: "Kill Bill",
    songImage: "coverarts/killbill.jpg",
    artist: "SZA",
    imgtxt: "killbill",
    month: "January",
  },
  {
    id: "4",
    no: "04",
    songName: "The Color Violet",
    songImage: "coverarts/thecolorviolet.jpg",
    artist: "Tory Lanez",
    imgtxt: "thecolorviolet",
    month: "January",
  },
  {
    id: "5",
    no: "01",
    songName: "Fukumean",
    songImage: "coverarts/fukumean.jpg",
    artist: "Gunna",
    imgtxt: "fukumean",
    month: "February",
  },
  {
    id: "6",
    no: "02",
    songName: "First Person Shooter",
    songImage: "coverarts/firstpersonshooter.jpg",
    artist: "Drake",
    imgtxt: "firstpersonshooter",
    month: "February",
  },
  {
    id: "7",
    no: "03",
    songName: "FE!N",
    songImage: "coverarts/fein.jpg",
    artist: "Travis Scott",
    imgtxt: "fein",
    month: "February",
  },
  {
    id: "8",
    no: "04",
    songName: "Never Lose Me",
    songImage: "coverarts/neverloseme.png",
    artist: "Flo Milli",
    imgtxt: "neverloseme",
    month: "February",
  },
];
